document.addEventListener("DOMContentLoaded",function(){const formContato=document.getElementById("form-contato");const formVoluntario=document.getElementById("form-voluntario");const formNewsletter=document.getElementById("form-newsletter");if(formContato){const nomeInput=document.getElementById("nome_cont");const mensagemInput=document.getElementById("mensagem");const nomeError=document.getElementById("error-nome");const mensagemError=document.getElementById("error-mensagem");const alertSucesso=document.getElementById("alert-sucesso");formContato.addEventListener("submit",function(event){event.preventDefault();nomeError.textContent="";mensagemError.textContent="";alertSucesso.style.display="none";nomeInput.setAttribute("aria-invalid","false");mensagemInput.setAttribute("aria-invalid","false");let isValid=!0;if(nomeInput.value.trim()===""){nomeError.textContent="Por favor, preencha seu nome.";nomeInput.setAttribute("aria-invalid","true");isValid=!1}
if(mensagemInput.value.trim().length<10){mensagemError.textContent="Sua mensagem deve ter pelo menos 10 caracteres.";mensagemInput.setAttribute("aria-invalid","true");isValid=!1}
if(isValid){alertSucesso.style.display="block";formContato.reset()}})}
if(formVoluntario){const alertSucesso=document.getElementById("alert-sucesso-voluntario");const nomeVol=document.getElementById("nome_vol");const emailVol=document.getElementById("email_vol");const telVol=document.getElementById("tel_vol");const nascVol=document.getElementById("nascimento");const areaVol=document.getElementById("area_interesse");const diasCheckboxes=document.querySelectorAll("input[name='dias']");const periodoRadios=document.querySelectorAll("input[name='periodo']");const nomeError=document.getElementById("error-nome-vol");const emailError=document.getElementById("error-email-vol");const telError=document.getElementById("error-tel-vol");const nascError=document.getElementById("error-nascimento-vol");const areaError=document.getElementById("error-area-vol");const diasError=document.getElementById("error-dias-vol");const periodoError=document.getElementById("error-periodo-vol");formVoluntario.addEventListener("submit",function(event){event.preventDefault();let isValid=!0;alertSucesso.style.display="none";nomeError.textContent="";emailError.textContent="";telError.textContent="";nascError.textContent="";areaError.textContent="";diasError.textContent="";periodoError.textContent="";nomeVol.setAttribute("aria-invalid","false");emailVol.setAttribute("aria-invalid","false");telVol.setAttribute("aria-invalid","false");nascVol.setAttribute("aria-invalid","false");areaVol.setAttribute("aria-invalid","false");if(nomeVol.value.trim()===""){nomeError.textContent="O nome é obrigatório.";nomeVol.setAttribute("aria-invalid","true");isValid=!1}
if(emailVol.value.trim()===""){emailError.textContent="O e-mail é obrigatório.";emailVol.setAttribute("aria-invalid","true");isValid=!1}
if(telVol.value.trim()===""){telError.textContent="O telefone é obrigatório.";telVol.setAttribute("aria-invalid","true");isValid=!1}
if(nascVol.value===""){nascError.textContent="A data de nascimento é obrigatória.";nascVol.setAttribute("aria-invalid","true");isValid=!1}
if(areaVol.value===""){areaError.textContent="Selecione uma área de interesse.";areaVol.setAttribute("aria-invalid","true");isValid=!1}
let diaSelecionado=!1;for(const checkbox of diasCheckboxes){if(checkbox.checked){diaSelecionado=!0;break}}
if(!diaSelecionado){diasError.textContent="Selecione pelo menos um dia.";isValid=!1}
let periodoSelecionado=!1;for(const radio of periodoRadios){if(radio.checked){periodoSelecionado=!0;break}}
if(!periodoSelecionado){periodoError.textContent="Selecione um período.";isValid=!1}
if(isValid){alertSucesso.style.display="block";formVoluntario.reset()}})}
if(formNewsletter){const emailInput=document.getElementById("email_news");const emailError=document.getElementById("error-email-news");const alertSucesso=document.getElementById("alert-sucesso-news");formNewsletter.addEventListener("submit",function(event){event.preventDefault();let isValid=!0;emailError.textContent="";alertSucesso.style.display="none";emailInput.setAttribute("aria-invalid","false");if(emailInput.value.trim()===""){emailError.textContent="O e-mail é obrigatório.";emailInput.setAttribute("aria-invalid","true");isValid=!1}
if(isValid){alertSucesso.style.display="block";formNewsletter.reset()}})}})